/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ConsultaSaldos;

import Bienvenida.login;
import CreditosPersonales.ComboItem;
import CreditosPersonales.datosPersonales;
import Dashboard.dashboardAdmin;
import Dashboard.dashboardUser;
//import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import estructuras.Lista;
import estructuras.Persona;
import java.awt.event.ItemEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fernando
 */
public class consulta extends javax.swing.JFrame {

    /**
     * Creates new form consulta
     */
    Lista lista = new Lista();
    DefaultTableModel modelo;
    int code = 0;
    DecimalFormat decimalFormat = new DecimalFormat("#.##");
        
    //sobrecarga
    public consulta(int code) {
        
        initComponents();
        this.code = code;
        
        try {
            this.Asociados();
        } catch (SQLException ex) {
            Logger.getLogger(consulta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        modelo = new DefaultTableModel();
        modelo.addColumn("Tipo");
        modelo.addColumn("Interes");
        modelo.addColumn("Amortizacion");
        modelo.addColumn("Monto");
        this.tabledata.setModel(modelo);
        jLabel1.setText(lista.datosPersona(code).getName()+" "+lista.datosPersona(code).getLast_name());
        
        
    }
    datosPersonales datosp = new datosPersonales();
    public consulta() {
        initComponents();
        try {
            this.Asociados();
        } catch (SQLException ex) {
            Logger.getLogger(consulta.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
        modelo = new DefaultTableModel();
        modelo.addColumn("Tipo");
        modelo.addColumn("Interes");
        modelo.addColumn("Amortizacion");
        modelo.addColumn("Monto");
        this.tabledata.setModel(modelo);
        jLabel1.setVisible(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        c_asociados = new javax.swing.JComboBox<ComboItem>();
        i_operaciones = new javax.swing.JComboBox<ComboItem>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledata = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(3, 41, 79));
        jPanel1.setFocusTraversalPolicyProvider(true);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Asociado");

        c_asociados.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        c_asociados.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c_asociadosItemStateChanged(evt);
            }
        });
        c_asociados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_asociadosActionPerformed(evt);
            }
        });
        c_asociados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c_asociadosKeyReleased(evt);
            }
        });

        i_operaciones.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        i_operaciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                i_operacionesItemStateChanged(evt);
            }
        });
        i_operaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_operacionesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Crédito");

        tabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabledata);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel1");

        jButton2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton2.setText("Atrás");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 169, 184));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 169, 184));
        jLabel4.setText("AseIsthmus");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Desloguearme");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(i_operaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(142, 142, 142)
                        .addComponent(c_asociados, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_asociados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(i_operaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c_asociadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_asociadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_asociadosActionPerformed

    private void i_operacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_operacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_operacionesActionPerformed
    
    public void AddOperacion(){
        
    }
    
    private void c_asociadosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c_asociadosItemStateChanged
        i_operaciones.removeAllItems();
        decimalFormat.setGroupingUsed(true);
        decimalFormat.setGroupingSize(3);
        if(evt.getStateChange() == ItemEvent.SELECTED)
        {

            Object item = c_asociados.getSelectedItem();
            String value = ((ComboItem)item).getValue();
            System.out.println("------");
            System.out.println(value);
          
            
            ResultSet resultado = null;
            resultado = datosp.Operaciones(Integer.parseInt(value));
            i_operaciones.addItem(new ComboItem( "Seleccione un Crédito", "-1"));
            System.out.println(resultado);
            try {
                while(resultado.next()){
                    // Lista
                    System.out.println(resultado.getObject(3));
                    
                    i_operaciones.addItem(new ComboItem("₡ "+decimalFormat.format(resultado.getObject(3)), ""+resultado.getObject(1)));
                         
                }
            } catch (SQLException ex) {
                System.out.println(ex);
                Logger.getLogger(consulta.class.getName()).log(Level.SEVERE, null, ex);
            }
             
        }
        
    }//GEN-LAST:event_c_asociadosItemStateChanged

    private void c_asociadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_asociadosKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_c_asociadosKeyReleased

    private void i_operacionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_i_operacionesItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == ItemEvent.SELECTED){
            DefaultTableModel model = (DefaultTableModel) tabledata.getModel();
            model.setRowCount(0);
            ResultSet resultado = null;
            Object item = i_operaciones.getSelectedItem();
            String value = ((ComboItem)item).getValue();
            
            resultado = datosp.MovOperaciones(Integer.parseInt(value));
             try {
                while(resultado.next()){
                    // Lista
                    System.out.println(resultado.getObject(3));
                    
                    String[] info = new String[8];
                    
                    info[0] = "" + resultado.getObject(7);
                    info[1] = ""+resultado.getObject(4);
                    info[2] = ""+resultado.getObject(5);
                    info[3] = "" + resultado.getObject(6);

                    modelo.addRow(info);
                         
                }
            } catch (SQLException ex) {
                System.out.println(ex);
                Logger.getLogger(consulta.class.getName()).log(Level.SEVERE, null, ex);
            }
              
        }
        
        
        
    }//GEN-LAST:event_i_operacionesItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dashboardAdmin da = new dashboardAdmin();
        da.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(code != 0){
            dashboardUser dd = new dashboardUser(code);
            dd.setVisible(true);
            this.dispose();
        }else{
            dashboardAdmin da = new dashboardAdmin();
            da.setVisible(true);
            this.dispose();
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        login login = new login();
        login.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked
    
    public void addCombo(Lista lista,int total){
    for(int i =0; i<=total;i++){
        Persona p = lista.GetCabeza();
        c_asociados.addItem(new ComboItem(""+p.getName()+" "+p.getLast_name(), ""+p.getUser_code()));
        lista.elimina(p.getUser_code());
                    
    
    }
    
    }
    
    public void Asociados() throws SQLException {
        ResultSet resultado = null;
        resultado = datosp.Asociados();
        if (resultado != null) {
            int numeroColumna = resultado.getMetaData().getColumnCount();
            c_asociados.addItem(new ComboItem( "Seleccione un Asociado", "-1"));
            
            int count=0;
            while(resultado.next()){
                    // Lista
                    System.out.println("code: "+code);
                    if(code !=0 ){
                       // System.out.println("******"+resultado.getObject(1)+"4444"+code);
                        if((int) resultado.getObject(2) == code){
                            lista.insertar(new Persona((int) resultado.getObject(1),""+resultado.getObject(2),""+resultado.getObject(3)));
                            count = 1;
                        
                        }
                    }else{
                    
                    lista.insertar(new Persona((int) resultado.getObject(1),""+resultado.getObject(2),""+resultado.getObject(3)));
                    count ++;
                    }
                    //c_asociados.addItem(new ComboItem(""+resultado.getObject(2)+" "+resultado.getObject(3), ""+resultado.getObject(1)));
                    
                    
                }
            addCombo(lista,count);
                    System.out.println(lista.toString());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<ComboItem> c_asociados;
    private javax.swing.JComboBox<ComboItem> i_operaciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tabledata;
    // End of variables declaration//GEN-END:variables
}
